config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :bookmarks
  end

  resources :bookmarks, only: [:destroy]


end
 # resources :movies do
  #   resources :bookmarks
  # end
# notice The shallow: true option is used to optimize the URL structure by only including the parent resource ID in the URL for the nested resource's "new" and "edit" actions. For all other actions, the parent resource ID is included in the URL as a parameter.
# resources :lists do
#   resources :bookmarks, shallow: true
# end

# resources :movies do
#   resources :bookmarks, shallow: true
# end

# GET "lists/42/bookmarks/new"
# POST "lists/42/bookmarks"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
  validates :overview, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    p "in the destroy method"
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end


  private

  def bookmark_params
      params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

# def new
#   @list = List.find(params[:list_id])
#   @bookmark = Bookmark.new
# end

# def create
#   @list = List.find(params[:list_id])
#   @bookmark = @list.bookmarks.new(bookmark_params)
# if @bookmark.save
# puts "saved"
# redirect_to @list
# else
# puts "not saved"
# render "new"
# end
# end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

def index
@lists = List.all
end

def show
@list = List.find(params[:id])
end


def new
    @list = List.new # Needed to instantiate the form_with
end

def create
@list = List.new(list_params)
if @list.save
  redirect_to @list
else
  render "new"
end
end

def destroy
  @list = List.find(params[:id])
  @list.destroy
  # No need for app/views/restaurants/destroy.html.erb
  redirect_to lists_path, status: :see_other
end


private

def list_params
  params.require(:list).permit(:name)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container"><h1>Add a movie</h1></div>

<%= simple_form_for([@list, @bookmark])  do |f| %>
<%= f.association :movie %>
<%= f.input :comment %>
  <%= f.submit %>
<% end %>

<p><<<%= link_to "Back to list", list_path(@list), class: "btn btn-flat" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MovieLists</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://localhost:3000/lists">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container"><h1>Lists</h1>

<% @lists.each do |item| %>
<p><%= link_to item.name, list_path(item) %></p>

<% end %>
<p><%= link_to "Create a movie list", new_list_path, class: "btn btn-flat" %></p>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

<p><%= link_to "Back to list of movies", lists_path, class: "btn btn-flat" %></p>

app/views/lists/show.html.erb
<h1>List</h1>

<h2><%= @list.name %></h2>
<div class="container">
<p><<<%= link_to "Back to Movie lists", lists_path, class: "btn btn-flat" %></p>

<% @list.movies.each do |movie| %>
<h3>Title</h3>
<p><%= movie.title %></p>
<h3>Overview</h3>
<p><%= movie.overview %></p>


  <% bookmark = Bookmark.find_by(list_id: @list.id, movie_id: movie.id) %>

<h3>Comment</h3>
<%= bookmark.comment %>
<hr>
<%= link_to "Delete this movie from list",
  bookmark_path(bookmark.id),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>

<hr>
<% end %>

<p>++<%= link_to "Add a movie to your list", new_list_bookmark_path(@list.id), class: "btn btn-flat" %></p>

<%= link_to "Delete this list",
  list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</div>